let header = document.getElementById("mainHeader");
let active = document.getElementsByClassName("active");
let links = document.getElementsByTagName("a");
let paragraph = document.getElementsByTagName("p");
let footer = document.getElementById("mainFooter");
let par = footer.getElementsByTagName("p");
console.log(header);
console.log(active);
console.log(links);
console.log(paragraph);
console.log(footer);
console.log(par);
